name: Test code

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: lint
      run: |
        cd javascript-client-generated
        npm i
        npm run lint
    - name: build
      run: |
        cd javascript-client-generated
        npm run build
    - name: test
      run: |
        cd javascript-client-generated
        npm run test 
      env:
        node_env: testing         
